version: 2.1

commands:
  install_dependencies:
    parameters:
      compilers:
        type: string
        default: ""
    steps:
      - run: 
          name: Install dependencies
          command: |
            apt-get update
            apt-get --assume-yes install make
            apt-get --assume-yes install bison flex
            apt-get --assume-yes install << parameters.compilers >>

  build_project:
    parameters:
      compiler:
        type: string
        default: ""
    steps:
      - run: 
          name: Build project with << parameters.compiler >>
          command: |
            export CC=<< parameters.compiler >>
            make
            make clean

jobs:
  Ubuntu-14-04:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - install_dependencies:
          compilers: gcc-4.7 gcc-4.8
      - build_project:
          compiler: gcc-4.7
      - build_project:
          compiler: gcc-4.8

  Ubuntu-16-04:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - install_dependencies:
          compilers: gcc-4.7 gcc-4.8 gcc-4.9 gcc-5
      - build_project:
          compiler: gcc-4.7
      - build_project:
          compiler: gcc-4.8
      - build_project:
          compiler: gcc-4.9
      - build_project:
          compiler: gcc-5

  Ubuntu-18-04:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - install_dependencies:
          compilers: gcc-4.8 gcc-5 gcc-6 gcc-7 gcc-8
      - build_project:
          compiler: gcc-4.8
      - build_project:
          compiler: gcc-5
      - build_project:
          compiler: gcc-6
      - build_project:
          compiler: gcc-7
      - build_project:
          compiler: gcc-8

  Ubuntu-20-04:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - install_dependencies:
          compilers: gcc-7 gcc-8 gcc-9 gcc-10
      - build_project:
          compiler: gcc-7
      - build_project:
          compiler: gcc-8
      - build_project:
          compiler: gcc-9
      - build_project:
          compiler: gcc-10

  Ubuntu-21-04:
    docker:
      - image: ubuntu:21.04
    steps:
      - checkout
      - install_dependencies:
          compilers: gcc-7 gcc-8 gcc-9 gcc-10 gcc-11
      - build_project:
          compiler: gcc-7
      - build_project:
          compiler: gcc-8
      - build_project:
          compiler: gcc-9
      - build_project:
          compiler: gcc-10
      - build_project:
          compiler: gcc-11

workflows:
  version: 2
  workflow:
    jobs:
      - Ubuntu-14-04
      - Ubuntu-16-04
      - Ubuntu-18-04
      #- Ubuntu-20-04
      #- Ubuntu-21-04